# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bencode_blatyo}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Allen Madsen"]
  s.date = %q{2010-02-02}
  s.description = %q{This gem has been renamed to bencodr. Use that one instead.}
  s.email = %q{blatyo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "autotest/discover.rb",
     "bencode_blatyo.gemspec",
     "lib/bencodr.rb",
     "lib/bencodr/dictionary.rb",
     "lib/bencodr/integer.rb",
     "lib/bencodr/list.rb",
     "lib/bencodr/parser.rb",
     "lib/bencodr/string.rb",
     "spec/bencodr/dictionary_spec.rb",
     "spec/bencodr/integer_spec.rb",
     "spec/bencodr/list_spec.rb",
     "spec/bencodr/parser_spec.rb",
     "spec/bencodr/string_spec.rb",
     "spec/bencode_spec.rb",
     "spec/samples/bencodr.rb.torrent",
     "spec/samples/mini.bencodr",
     "spec/samples/python.torrent",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/blatyo/bencodr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This gem has been renamed to bencodr. Use that one instead.}
  s.test_files = [
    "spec/bencodr/dictionary_spec.rb",
     "spec/bencodr/integer_spec.rb",
     "spec/bencodr/list_spec.rb",
     "spec/bencodr/parser_spec.rb",
     "spec/bencodr/string_spec.rb",
     "spec/bencode_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

